### ISSUE TITLE
You can avoid users needing to install syntax-jsx

### ISSUE THREAD

**Issue by loganfsmyth** [trueadm/babel-plugin-inferno#20]
Was looking at this module investigating an unrelated issue and noticed your current setup requires users to enable the syntax plugin, so wanted to comment. You should be able to include `babel-plugin-syntax-jsx` as a dependency of this plugin itself to avoid your users needing to think about it. As long as its in your `dependencies` and you use [`inherits`](https://github.com/trueadm/babel-plugin-inferno/blob/master/lib/index.js#L250) like you already do, it should just work.

**Comment by trueadm** [comment]
@loganfsmyth Thanks for that, I've made the change to `package.json` and published it. :)

**Comment by loganfsmyth** [comment]
Happy to help :)
