### ISSUE TITLE
Is Inferno's compiled virtual DOM syntactically different from React's?

### ISSUE THREAD

**Issue by callumlocke** [trueadm/babel-plugin-inferno#24]
From the README:

> This plugin transforms JSX code in your projects to Inferno compatible virtual DOM.

In what way is that different from React-compatible virtual DOM?

**Comment by trueadm** [comment]
@callumlocke Inferno's virtual DOM is not the same as React's. It's completely different as Inferno will attempt to make blueprints. This shouldn't be an issue though for coming from a React codebase to Inferno.

**Comment by callumlocke** [comment]
Ok thanks. It would be interesting to see in the readme how the examples compile.

**Comment by Havunen** [comment]
Clone this repo, do npm install, and then run 
```
node example.js
```

**Comment by callumlocke** [comment]
Sure, I've done that, just making a suggestion for the readme. Think it's of interest to new users.

**Comment by developwithpassion** [comment]
Is the spread operator broken in the current version?

**Comment by trueadm** [comment]
@developwithpassion what version are you using?

**Comment by developwithpassion** [comment]
Quick response!! 0.7.7

**Comment by trueadm** [comment]
@developwithpassion It shouldn't be. What issues are you finding?

**Comment by developwithpassion** [comment]
Trying to compile this line:

              <View {...attributes}></View>

Attributes is just a plain object. If I take out the use of the spread attribute, I have no issues, when I include it I get the dreaded "May need a loader error", I'm using webpack, and without the use of the spread operator it compiles without issue, and dispatches to the appropriate Inferno builder methods.

**Comment by developwithpassion** [comment]
The error I'm getting is "You may need an appropriate loader to handle this file type"

**Comment by developwithpassion** [comment]
If you want to take this out of the discussion channel, I'll be happy to run a tmate session with you and pay you for the time you take.

**Comment by trueadm** [comment]
@developwithpassion I've not seen that issue with webpack. It obviously depends on the `babel-loader`. I'd be happy to help whatever, no cost involved.

**Comment by developwithpassion** [comment]
I'm a dad too, and a coder. Time is your most valuable resource, you'd be helping me out with something related to my work (which I'm getting paid for), so it's no problem (assuming you have a paypal account 👍 )

**Comment by developwithpassion** [comment]
Are you on skype?

**Comment by trueadm** [comment]
Sure "trueadm" on Skype.

**Comment by developwithpassion** [comment]
Give me 2 minutes

**Comment by trueadm** [comment]
Closing is that is covering by the main Inferno repo.
