### ISSUE TITLE
error in description of .babelrc file

### ISSUE THREAD

**Issue by davidmoshal** [trueadm/babel-plugin-inferno#4]
your `.babelrc` file is missing a comma - interestingly babel didn't output a clear message.

```js
{   
    "presets": [ "es2015", "stage-0" ]
    "plugins": ["babel-plugin-syntax-jsx", "babel-plugin-inferno"]
}
```

should be:

```js
{   
    "presets": [ "es2015", "stage-0" ],
    "plugins": ["babel-plugin-syntax-jsx", "babel-plugin-inferno"]
}
```
note the comma after ["stage-0"]

**Comment by trueadm** [comment]
@davidmoshal Thanks for the issue. This was a typo in the readme :)

**Comment by davidmoshal** [comment]
you are quick, just like your project!
